config/routes.rb
Rails.application.routes.draw do
  root "pages#index"

  resources :pools, only: [:show], path: 'p'
  resources :pulses, only: [:show, :destroy]

  scope module: "api", as: "pulse_request" do
    match "pulse/:id", to: "pulses#create", via: :all
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/pool.rb
class Recently
  def call(from = 2)
    Pool.where(created_at: from.days.ago)
  end
end

class Pool < ApplicationRecord
  include Hashid::Rails

  has_many :pulses, dependent: :destroy

  def create_pulse(params)
    pulses.create!()
  end

  # scope :recently, ->(from = 2) { where(created_at: from.days.ago) }
  scope :recently, Recently.new
end

app/models/pulse.rb
class Pulse < ApplicationRecord
  include Hashid::Rails

  belongs_to :pool, counter_cache: :pulses_count

  scope :newest_first, -> { order(id: :desc) }

  after_create_commit :broadcast_pulse_creation
  after_destroy_commit -> { broadcast_remove_to pool, target: "#{self.hashid}_item" }

  def broadcast_pulse_creation
    broadcast_prepend_to pool,
                         target: "pulses",
                         html: ApplicationController.render(PulseItemComponent.new(pulse_item: self), layout: false)

    broadcast_replace_to pool,
                         target: :header_pulse_list,
                         html: ApplicationController.render(HeaderListComponent.new(pool: self.pool), layout: false)
  end

  def json_header
    JSON.parse headers.gsub('=>', ':')
  end
end

app/models/pulses/request_params.rb
module Pulses
  class RequestParams
    NOT_ALLOWED_HEADERS = %w[HTTP_UPGRADE_INSECURE_REQUESTS HTTP_COOKIE]

    def initialize(request:)
      @request = request
    end

    def call
      {
        headers: headers,
        http_method: http_method,
        query_string: query_string,
        content_type: content_type,
        body: body,
        ip: ip,
        size: size,
        form_params: form_params
      }
    end

    private

    def headers
      @request.env.select {|k,v| k =~ /^HTTP_/}.delete_if { |k,_| NOT_ALLOWED_HEADERS.include?(k) }
    end
  
    def http_method
      @request.headers["REQUEST_METHOD"]
    end
  
    def query_string
      @request.env["rack.request.query_hash"]
    end
  
    def content_type
      @request.content_type
    end
  
    def body
      @request.body.read
    end
  
    def ip
      @request.ip
    end
  
    def size
      @request.env["CONTENT_LENGTH"].to_i
    end
  
    def form_params
      @request.env["rack.request.form_hash"]
    end
  end
end

app/models/request.rb
class Request < ApplicationRecord
  include Hashid::Rails

  belongs_to :pool

  scope :received, -> { order(id: :desc) }

  after_create_commit  { broadcast_prepend_to pool }
  after_destroy_commit { broadcast_remove_to pool }
end

app/controllers/api/base_controller.rb
class Api::BaseController < ActionController::Base
  skip_before_action :verify_authenticity_token
  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  private

  def not_found(e)
    head :not_found
  end
end

app/controllers/api/pulses_controller.rb
class Api::PulsesController < Api::BaseController
  before_action :check_allowed_methods
  before_action :set_pool

  def create
    @pool.pulses.create!(pulse_params)
    head :ok
  end

  private

  def set_pool
    @pool = Pool.find_by_hashid!(params[:id])
  end

  def pulse_params
    Pulses::RequestParams.new(request: request).call
  end

  def check_allowed_methods
    unless allowed_methods.include?(request.method_symbol)
      head :method_not_allowed
    end
  end

  def allowed_methods
    Constants::HTTP_METHODS
  end
end

app/controllers/api_controller.rb
class ApiController < ActionController::Base
  skip_before_action :verify_authenticity_token

  rescue_from ActiveRecord::RecordNotFound, with: :not_found

  private

  def not_found(e)
    head :not_found
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/hook/requests_controller.rb
class Hook::RequestsController < ApiController
  before_action :set_pool

  def create
    request_service = RequestService.new(request)      

    @request = @pool.requests.create!(
      ip: request_service.ip,
      size: request_service.size,
      body: request_service.body,
      headers: request_service.headers,
      form_params: request_service.form_params,
      http_method: request_service.http_method,
      query_string: request_service.query_string,
      content_type: request_service.content_type
    )

    head :ok
  end

  private

  def set_pool
    @pool = Pool.find_by_hashid!(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
    find_or_initialize_pool_cookie
  end

  private

  def find_or_initialize_pool_cookie
    if hashid = cookies.encrypted[:_session_pool_id]
      redirect_to pool_path(hashid)
    else
      pool = Pool.create!
      cookies.encrypted[:_session_pool_id] = pool.hashid
      redirect_to pool_path(pool)
    end
  end
end

app/controllers/pools_controller.rb
class PoolsController < ApplicationController
  before_action :set_pool

  def show
    @pulses = @pool.pulses.newest_first
  end
  
  private

  def set_pool
    @pool = Pool.find_by_hashid!(params[:id])
  rescue ActiveRecord::RecordNotFound
    cookies.delete(:_session_pool_id)
    redirect_to root_path
  end
end

app/controllers/pulses_controller.rb
class PulsesController < ApplicationController
  before_action :set_pulse

  def show
    render PulseComponent.new(pulse: @pulse)
  end

  def destroy
    @pool = @pulse.pool
    @pulse.destroy

    respond_to do |format|
      format.turbo_stream
    end
  end

  private

  def set_pulse
    @pulse = Pulse.find_by_hashid!(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pulse_helper.rb
module PulseHelper
  HTTP_TAG_COLORS = {
    "GET" => "text-bg-success",
    "POST" => "text-bg-primary",
    "PUT" => "text-bg-warning",
    "PATCH" => "text-bg-secondary",
    "DELETE" => "text-bg-danger",
    "OPTIONS" => "text-bg-info"
  }.freeze

  def http_tag(http_method)
    HTTP_TAG_COLORS[http_method]
  end
end

app/views/layouts/_header.html.erb
<header class="p-3 text-bg-dark">
  <div class="container">
    <div class="d-flex flex-wrap align-items-center justify-content-center">
      <a href="/" class="d-flex align-items-center text-white text-decoration-none">
        <%= image_tag 'logo.png', width: "40px", height: "32px", class: 'me-2' %>
      </a>
    </div>
  </div>
</header>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Inspecta - Inspect HTTP Requests with Ease</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
    <%= render 'layouts/header' %>

    <main class="container-fluid p-0">
      <%= yield %>
    </main>
  </body>
</html>

app/views/pools/_empty_state.html.erb
<%= turbo_frame_tag :pulse_details do %>
  <div class="d-flex flex-column gap-2 border rounded p-3">
    <div class="border-bottom">
      <p>Welcome to Inspecta.</p>
      <p>Inspect HTTP Requests with Ease - Your tool for Analyzing Request Details</p>
    </div>

    <div>
      <p><strong>This is your unique URL:</strong></p>
      <p class="fs-5 font-monospace bg-primary badge"><%= pulse_request_url(pool.hashid) %></p>
    </div>

    <div>
      <span class="fst-italic">Requests to your unique URL are instantly logged here without the need for refreshing.</span>
    </div>
  </div>
<% end %>

app/views/pools/show.html.erb
<%= turbo_stream_from @pool %>

<div class="d-flex flex-row p-0">
  <div class="col-md-3 col-sm-12 py-4 bg-light border-dark-subtl border-end full-height">
    <%= render HeaderListComponent.new(pool: @pool) %>
    
    <div id="pulses" class="d-flex flex-column gap-1">
      <%= render PulseItemComponent.with_collection(@pulses), class: 'animate__fadeIn' %>
    </div>
  </div>

  <div class="col-md-9 col-sm-12 p-3">
    <% if @pulses.any? %>
      <%= render PulseComponent.new(pulse: @pulses.first) %>
    <% else %>
      <%= render EmptyStateComponent.new(pool: @pool) %>
    <% end %>
  </div>
</div>

app/views/pulses/_header_list.html.erb
<%= turbo_frame_tag :header_pulse_list do %>
  <header class="mb-3 d-flex flex-column justify-content-center">
    <span class="text-center">
      Requests: (<%= quantity_of_pulses %>/<%= total_pulses %>)
    </span>
  </header>

  <hr>

  <% if quantity_of_pulses.zero? %>
    <div class="d-flex justify-content-center align-items-center gap-2">
      <div class="spinner-grow spinner-grow-sm text-info" role="status">
        <span class="visually-hidden">Loading...</span>
      </div>
      <span>Waiting for requests</span>
    </div>
  <% end %>
<% end %>

app/views/pulses/_pulse_details.html.erb
<%= turbo_frame_tag :pulse_details do %>
  <div class="d-flex flex-column gap-2">
    <div class="d-flex gap-4">
      <div class="w-100">
        <table class="table table-hover table-sm table-striped">
          <thead>
            <tr>
              <th colspan="2">Request Details</th>
            </tr>
          </thead>
          <tbody class="table-group-divider">
            <tr>
              <td><span class="rounded p-1 <%= http_tag(pulse.http_method) %>"><%= pulse.http_method %></span></td>
              <td><%= pulse_request_url(pool.hashid) %></td>
            </tr>
            <tr>
              <td>Host</td>
              <td><%= pulse.ip %></td>
            </tr>
            <tr>
              <td>Date</td>
              <td><%= l(pulse.created_at, format: :with_sec) %> - (<%= time_ago_in_words(pulse.created_at) %> ago)</td>
            </tr>
            <tr>
              <td>Size</td>
              <td><%= pulse.size %> bytes</td>
            </tr>
            <tr>
              <td>ID</td>
              <td><%= pulse.hashid %></td>
            </tr>
          </tbody>
        </table>
      </div>
      <div class="w-100">
        <table class="table table-hover table-sm table-striped">
          <thead>
            <tr>
              <th colspan="2">Headers</th>
            </tr>
          </thead>
          <tbody class="table-group-divider">
            <% pulse.headers.each do |key, value| %>
              <tr>
                <td><%= key.gsub(/^HTTP_/, '').downcase %></td>
                <td><%= value %></td>
              </tr>
            <% end %>
            <tr>
              <td>content-type</td>
              <td><%= pulse.content_type %></td>
            </tr>
          </tbody>
        </table>
      </div>
    </div>

    <h5>Body</h5>
    <div class="bg-light rounded p-2">
      <%= pulse.body %>
    </div>
  </div>

<% end %>

app/views/pulses/destroy.turbo_stream.erb
<%= turbo_stream.replace(:header_pulse_list) do %>
  <%= render HeaderListComponent.new(pool: @pool) %>
<% end %>

<%= turbo_stream.remove("#{@pulse.hashid}_item") %>

<%= turbo_stream.replace(:pulse) do %>
  <% if @pool.pulses.exists? %>
    <%= render PulseComponent.new(pulse: @pulse) %>
  <% else %>
    <%= render EmptyStateComponent.new(pool: @pool) %>
  <% end %>
<% end %>